name: Dependency Graph
on:
  workflow_run:
    workflows: ["Check"]
    branches: [10.0.x]
    types:
      - completed

concurrency:
  # Only run once for latest commit per ref and cancel other (previous) runs.
  group: dependency-graph-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: write # this permission is needed to submit the dependency graph

jobs:
  dependency-graph:
    name: Submit dependencies to GitHub
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.ref }}
      - uses: scalacenter/sbt-dependency-submission@v3 # for root project
      - uses: scalacenter/sbt-dependency-submission@v3
        with:
          working-directory: ./samples/compile-timeDI/
      - uses: scalacenter/sbt-dependency-submission@v3
        with:
          working-directory: ./samples/runtimeDI/
