name: Publish

on:
  push:
    branches: # Snapshots
      - 9.0.x
    tags: ["**"] # Releases
  release:
    types: [published]

jobs:
  publish-artifacts:
    name: Publish / Artifacts
    uses: playframework/.github/.github/workflows/publish.yml@v3
    secrets: inherit
